services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tweet_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   restart: always
  #   ports:
  #     - "6379:6379"

  postgres-admin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pgdata:
